{% set version = '1.1.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-prais
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/prais_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/prais/prais_{{ version }}.tar.gz
  sha256: fd31e13b2e4c4772114985e60ad7d5b35d3ef2c1edba25d203769b4cc339039a

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-lmtest
    - r-pcse
    - r-sandwich
  run:
    - r-base
    - r-lmtest
    - r-pcse
    - r-sandwich

test:
  commands:
    - $R -e "library('prais')"           # [not win]
    - "\"%R%\" -e \"library('prais')\""  # [win]

about:
  home: https://github.com/franzmohr/prais
  license: GPL-2.0-only
  summary: The Prais-Winsten estimator (Prais & Winsten, 1954) takes into account AR(1) serial
    correlation of the errors in a linear regression model. The procedure recursively
    estimates the coefficients and the error autocorrelation of the specified model
    until sufficient convergence of the AR(1) coefficient is attained.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - pn-alex

# Package: prais
# Type: Package
# Title: Prais-Winsten Estimator for AR(1) Serial Correlation
# Version: 1.1.2
# Authors@R: person("Franz X.", "Mohr", email = "prais.r@outlook.com", role = c("aut","cre"))
# Description: The Prais-Winsten estimator (Prais & Winsten, 1954) takes into account AR(1) serial correlation of the errors in a linear regression model. The procedure recursively estimates the coefficients and the error autocorrelation of the specified model until sufficient convergence of the AR(1) coefficient is attained.
# License: GPL-2
# Depends: R (>= 3.2.0), sandwich, pcse
# Imports: lmtest, stats
# RoxygenNote: 7.1.2
# URL: https://github.com/franzmohr/prais
# BugReports: https://github.com/franzmohr/prais/issues
# Collate: 'prais_winsten.R' 'print.prais.R' 'summary.prais.R' 'print.summary.prais.R' 'pw_transform.R' 'vcovHC.R' 'vcovPC.R' 'zzz.R'
# NeedsCompilation: no
# Packaged: 2021-11-01 14:50:16 UTC; franz
# Author: Franz X. Mohr [aut, cre]
# Maintainer: Franz X. Mohr <prais.r@outlook.com>
# Repository: CRAN
# Date/Publication: 2021-11-01 15:50:02 UTC
